export const UPDATE_MOVIE_RESULTS = 'UPDATE_MOVIE_RESULTS';
export const NOMINATE_MOVIE = 'NOMINATE_MOVIE';
export const UPDATE_SEARCH_STRING = 'UPDATE_SEARCH_STRING';
export const UPDATE_RESULTS_PAGES = 'UPDATE_RESULTS_PAGES';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
